### ISSUE TITLE
image pull err

### ISSUE THREAD

**Issue by lkad** [tencentmusic/argo-workflow#4]
docker pull ai.tencentmusic.com/tme-public/kubeflow-dashboard:argo-2022.05.01
Trying to pull repository ai.tencentmusic.com/tme-public/kubeflow-dashboard ... 
repository ai.tencentmusic.com/tme-public/kubeflow-dashboard not found: does not exist or no pull access

 how can i download the images

**Comment by data-infra** [comment]
直接使用cube-studio项目

**Comment by lkad** [comment]
> 直接使用cube-studio项目

谢谢
